-- 从截图录入 10 家新中转站
-- 数据来源: C:\Users\Administrator\Pictures\新建文件夹\ScreenShot_2026-08-11_165*.png
-- 时间: 2026-08-11

INSERT INTO providers (
  slug, name, website_url, description, features,
  is_recommended, status, sort_order,
  min_topup, trial_credit, transaction_fee, invoice_support,
  promo_code, verification_status, verified_at
) VALUES
  (
    'h-api',
    'H API',
    NULL, -- 截图未显示官网
    '站长跑路风险，首充赠送',
    ARRAY['apiranking 老板密码'],
    false,
    'published',
    0,
    '200元起充',
    '$0.5',
    '1.6%手续费',
    false,
    'apiranking',
    'pending', -- 截图标记为红色告警，但有"通过检测"绿色标签矛盾，暂设 pending
    NULL
  ),
  (
    'openox',
    'OpenOx',
    NULL,
    '看信还是老板跑路，月卡每天66%',
    ARRAY['3%送回来$3'],
    false,
    'published',
    0,
    '无手续费',
    '如送条幅免$3',
    '无手续费',
    false,
    NULL,
    'verified',
    NOW()
  ),
  (
    'linkai',
    'LinkAI',
    NULL,
    '我们公司在这个站上海第10000多了',
    ARRAY['本站目录自动选择的化重'],
    false,
    'published',
    0,
    '200元起充',
    '进群赠送',
    '无手续费',
    false,
    NULL,
    'verified',
    NOW()
  ),
  (
    'uu-api',
    'UU API',
    NULL,
    '【本站用户专属】首充赠 10%送换券',
    ARRAY['apiranking', '老板密码'],
    false,
    'published',
    0,
    '3%手续费',
    '进群赠送',
    '3%手续费',
    false,
    NULL,
    'verified',
    NOW()
  ),
  (
    'apinebula',
    'APINebula',
    NULL,
    '【本站用户专属】首充赠10%送换券',
    ARRAY['apiranking', '老板密码'],
    false,
    'published',
    0,
    '无手续费',
    'V20',
    '无手续费',
    false,
    NULL,
    'verified',
    NOW()
  ),
  (
    'runapi',
    'RunAPI',
    NULL,
    NULL,
    ARRAY[],
    false,
    'published',
    0,
    '无手续费',
    '$0.1',
    '无手续费',
    false,
    'V7',
    'verified',
    NOW()
  ),
  (
    'linksapi',
    'LinksAPI',
    NULL,
    '月卡至30%',
    ARRAY['本站用户尤$5'],
    false,
    'published',
    0,
    '无手续费',
    '本站用户尤$5',
    '无手续费',
    false,
    'V9.9',
    'verified',
    NOW()
  ),
  (
    'lmu-ai',
    'LMU AI·灵眸',
    NULL,
    NULL,
    ARRAY[],
    false,
    'published',
    0,
    '无手续费',
    NULL,
    '无手续费',
    false,
    'V1',
    'verified',
    NOW()
  ),
  (
    'santouniu',
    '三头牛',
    NULL,
    NULL,
    ARRAY[],
    false,
    'published',
    0,
    '100元起充',
    'V7',
    '1%手续费',
    false,
    'V7',
    'verified',
    NOW()
  ),
  (
    'boxying',
    'boxying',
    NULL,
    '【本站用户专属】首充送5%优惠券',
    ARRAY['apiranking', '老板密码'],
    false,
    'published',
    0,
    '无手续费',
    '$0.5',
    '无手续费',
    false,
    NULL,
    'verified',
    NOW()
  );

COMMENT ON COLUMN providers.slug IS '转录说明：截图分辨率有限，部分字段（如 description/features）可能混淆了"赠送"与"优惠码"、"手续费"与"起充"。录入后需人工核对官网原文并修正。H API 标记为 pending 是因为截图同时显示红色告警和绿色"通过检测"标签，状态矛盾。';
